FineWineApp.Web/Models/Wine.cs
using Microsoft.AspNetCore.Mvc.Formatters;
using System.ComponentModel.DataAnnotations;

namespace FineWineApp.Web.Models;

public class Wine
{
    public int Id { get; set; }

    [Required]
    public string Name { get; set; }

    [Required]
    public string WineMaker { get; set; }

    [Required]
    public decimal Price { get; set; }

    [Required]
    public int Year { get; set; }

    [Required]
    public string Country { get; set; }

    [Required]
    public float AlcPercentage { get; set; }

    [Required]
    public string Description { get; set; }

    [Required]
    public string Type { get; set; }

    public string ImagePath { get; set; }

    public IFormFile ImageFile { get; set; }

}

FineWineApp.Web/Controllers/WinesController.cs
using FineWineApp.Web.Services;
using Microsoft.AspNetCore.Mvc;
using FineWineApp.Web.Models;

namespace FineWineApp.Web.Controllers;
public class WinesController : Controller
{
    WineService wineService = new WineService();

    [Route("")]
    public IActionResult Index()
    {
        Wine[] wines = wineService.GetAllWines();
        return View(wines);
    }

    [Route("wines/{wineId}")]
    public IActionResult Info(int wineId)
    {
        Wine wine = wineService.GetWineById(wineId);
        return View(wine);
    }

    [HttpGet("create")]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost("create")]
    public async Task<IActionResult> Create(Wine wine, IFormFile ImageFile)
    {
        if (ImageFile != null && ImageFile.Length > 0)
        {
            var fileName = Path.GetFileName(ImageFile.FileName);
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images", fileName);

            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                await ImageFile.CopyToAsync(stream);
            }

            // Spara bara filnamnet i objektet
            wine.ImagePath = fileName;
        }

        // Generera Id (eftersom vi inte har DB som gör det åt oss)
        wineService.AddWine(wine);

        return RedirectToAction("Index");
    }
}

FineWineApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://unpkg.com/@@picocss/pico@@latest/css/pico.classless.min.css">
	<link href="~/design/design.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    @* <h1>Fine Wine AB</h1> *@
    <div>
        @RenderBody()
    </div>

    <footer> &copy; Fine Wine AB </footer>

    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.7.1.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>

FineWineApp.Web/Views/Wines/Create.cshtml
@{
	ViewBag.Title = "Create";
}

@model Wine
	<h4>Add new wine</h4>
	
<div class="CreateForm">
	<form asp-controller="Wines" asp-action="Create" enctype="multipart/form-data" method="post"> 
		<label asp-for="Name"></label>
		<span asp-validation-for="Name" style="color: red"></span>
		<input asp-for="Name" />

		<label asp-for="WineMaker"></label>
		<span asp-validation-for="WineMaker" style="color: red"></span>
		<input asp-for="WineMaker" />

		<label asp-for="Price"></label>
		<span asp-validation-for="Price" style="color: red"></span>
		<input asp-for="Price" />

		<label asp-for="Year"></label>
		<span asp-validation-for="Year" style="color: red"></span>
		<input asp-for="Year" />

		<label asp-for="Country"></label>
		<span asp-validation-for="Country" style="color: red"></span>
		<input asp-for="Country" />

		<label asp-for="AlcPercentage"></label>
		<span asp-validation-for="AlcPercentage" style="color: red"></span>
		<input asp-for="AlcPercentage" />

		<label asp-for="Description"></label>
		<span asp-validation-for="Description" style="color: red"></span>
		<input asp-for="Description" />

		<label asp-for="Type"></label>
		<span asp-validation-for="Type" style="color: red"></span>
		<input asp-for="Type" />

		<label asp-for="ImageFile">Add image</label>
		<input asp-for="ImageFile" type="file" />
		<br />

		<button type="submit">Save</button>
	</form>
</div>

@section scripts
{
	<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.2/jquery.validate.min.js"></script>
	<script src="https://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"></script>
}

FineWineApp.Web/Views/Wines/Index.cshtml
@{
	ViewBag.Title = "Home";
}
@model Wine[]
<div class="IndexDiv">
	<h1>Wine in stock</h1>
		<div class="IndexList">
			<ul>
				@foreach (var wine in Model)
				{
					<li>
						<a style="text-decoration: none" 
							asp-controller="Wines"
							asp-action="Info"
							asp-route-wineId="@wine.Id">@wine.Name (@wine.Type) - @wine.Price:-</a>
					</li>
				}
			</ul>

			<a asp-controller="Wines" asp-action="Create">Add wine</a>

		</div>
</div>

FineWineApp.Web/Views/Wines/Info.cshtml
@{
    ViewBag.Title = "Info";
}
@model Wine
<title>Info</title>

<img src="@Url.Content("~/Images/" + Model.ImagePath)"/>


<h1>@Model.Name</h1>

<h6>Winemaker:</h6>
    <p>@Model.WineMaker</p>

<h6>Country:</h6>
    <p>@Model.Country</p>

<h6>Year:</h6>
    <p>@Model.Year</p>

<h6>DESCRIPTION:</h6>
    <p>@Model.Description</p>


<div>
    <a asp-controller="Wines" asp-action="Index">
        <button>Go back</button>
    </a>
</div>